"""initial

Revision ID: 2506ddcf9e21
Revises: 
Create Date: 2025-01-21 05:01:28.804631

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2506ddcf9e21"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_contact_statuses_name", "contact_statuses", ["name"], unique=False
    )
    op.create_table(
        "forecast_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "idx_forecast_categories_name", "forecast_categories", ["name"], unique=False
    )
    op.create_table(
        "industries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_industries_name", "industries", ["name"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_products_name", "products", ["name"], unique=False)
    op.create_table(
        "stages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_stages_name", "stages", ["name"], unique=False)
    op.create_table(
        "companies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("size", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("is_customer", sa.Boolean(), nullable=False),
        sa.Column("annual_revenue", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["industry_id"],
            ["industries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
    )
    op.create_index("idx_companies_domain", "companies", ["domain"], unique=False)
    op.create_index(
        "idx_companies_industry_id", "companies", ["industry_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["contact_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_contacts_company_id", "contacts", ["company_id"], unique=False)
    op.create_index("idx_contacts_email", "contacts", ["email"], unique=False)
    op.create_index("idx_contacts_status_id", "contacts", ["status_id"], unique=False)
    op.create_table(
        "opportunities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("company_id", sa.String(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("forecast_category_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("probability", sa.Integer(), nullable=False),
        sa.Column("created_date", sa.DateTime(), nullable=False),
        sa.Column("close_date", sa.DateTime(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_category_id"],
            ["forecast_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_opportunities_company_id", "opportunities", ["company_id"], unique=False
    )
    op.create_index(
        "idx_opportunities_contact_id", "opportunities", ["contact_id"], unique=False
    )
    op.create_index(
        "idx_opportunities_forecast_category_id",
        "opportunities",
        ["forecast_category_id"],
        unique=False,
    )
    op.create_index(
        "idx_opportunities_product_id", "opportunities", ["product_id"], unique=False
    )
    op.create_index(
        "idx_opportunities_stage_id", "opportunities", ["stage_id"], unique=False
    )
    op.create_table(
        "activities",
        sa.Column("contact_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("opportunity_id", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_activities_contact_id", "activities", ["contact_id"], unique=False
    )
    op.create_index(
        "idx_activities_opportunity_id", "activities", ["opportunity_id"], unique=False
    )
    op.create_index(
        "idx_activities_timestamp", "activities", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_activities_timestamp", table_name="activities")
    op.drop_index("idx_activities_opportunity_id", table_name="activities")
    op.drop_index("idx_activities_contact_id", table_name="activities")
    op.drop_table("activities")
    op.drop_index("idx_opportunities_stage_id", table_name="opportunities")
    op.drop_index("idx_opportunities_product_id", table_name="opportunities")
    op.drop_index("idx_opportunities_forecast_category_id", table_name="opportunities")
    op.drop_index("idx_opportunities_contact_id", table_name="opportunities")
    op.drop_index("idx_opportunities_company_id", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("idx_contacts_status_id", table_name="contacts")
    op.drop_index("idx_contacts_email", table_name="contacts")
    op.drop_index("idx_contacts_company_id", table_name="contacts")
    op.drop_table("contacts")
    op.drop_index("idx_companies_industry_id", table_name="companies")
    op.drop_index("idx_companies_domain", table_name="companies")
    op.drop_table("companies")
    op.drop_index("idx_stages_name", table_name="stages")
    op.drop_table("stages")
    op.drop_index("idx_products_name", table_name="products")
    op.drop_table("products")
    op.drop_index("idx_industries_name", table_name="industries")
    op.drop_table("industries")
    op.drop_index("idx_forecast_categories_name", table_name="forecast_categories")
    op.drop_table("forecast_categories")
    op.drop_index("idx_contact_statuses_name", table_name="contact_statuses")
    op.drop_table("contact_statuses")
    # ### end Alembic commands ###
