name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-lint-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Check lint and formatting
        run: make check-lint-and-formatting

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run ETL pipeline tests
        run: make tests
